# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('munros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mountain',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
